services:
  server:
    build: .
    networks:
      - traefik-proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.vlott.rule=Host(`vlott.dk-gl.eu`)
      - traefik.http.routers.vlott.entrypoints=https
      - traefik.http.services.vlott-server.loadbalancer.server.port=80
    restart: always
    volumes:
      - ./versions/v2/overrides/:/app/versions/v2/overrides/
networks:
  traefik-proxy:
    external: true
    name: traefik-proxy
