import os
import csv
import logging
import json

from utils.cache.timed import timed_lru_cache

@timed_lru_cache(seconds=60*60*24)
def parse():
	"""
	Parse tables generated by tools/ggroup_conv.py
	Excpects a file on path "versions/v2/overrides/gdata.tsv".
	Overrides are added to "versions/v2/overrides/teachers.json" as a typical
	key-value dictionary.
	"""
	if not os.path.exists("versions/v2/overrides/gdata.tsv"):
		logging.error("file \"versions/v2/overrides/gdata.tsv\" not found, aborting")
		exit(1)

	fh = open("versions/v2/overrides/gdata.tsv", "r")
	table = {}

	if os.path.exists("versions/v2/overrides/teachers.json"):
		ovr = open("versions/v2/overrides/teachers.json", "r")
		for k,v in json.load(ovr).items():
			table[k.lower()] = v

	for _, name in csv.reader(fh, delimiter=";"):
		fname, sname = name.split()
		table[f"{sname}{fname[0]}".lower()] = name
		table[f"{sname}_{fname[0]}".lower()] = name
		table[name.lower()] = name
		
		if "-" in sname:
			for part in sname.split("-"):
				table[f"{part}_{fname[0]}".lower()] = name
				table[f"{part}{fname[0]}".lower()] = name

	fh.close()
	return table
